name: Protobuf checking

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.18.1
      - name: Linting
        run: buf check lint

  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 2
      - uses: wizhi/actions-buf@v1
        with:
          version: 0.18.0
      - run: >
          git checkout HEAD^;
          buf image build --output previous.bin;
          git checkout ${{ github.ref }};
      - run: buf check breaking --against-input previous.bin

