name: Protobuf checking

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.44.0
      - name: Linting
        run: buf check lint

  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.44.0
      - run: buf check breaking --against-input ".git#ref=${{ github.ref }}^"

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.44.0
      - run: buf -v
