name: Protobuf checking

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@be4301d81a716d677b5376281d647966c11e70ad
      - name: Linting
        run: buf check lint

  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: wizhi/setup-buf@be4301d81a716d677b5376281d647966c11e70ad
      - run: buf check breaking --against-input ".git#ref=${{ github.ref }}^"

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@development
      - run: buf -v
